services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php_app
    container_name: telegram-bot-php
    restart: always
    depends_on:
      - db
    volumes:
      - '/var/www/app/vendor'
#      - './:/var/www/app'

  db:
    image: postgres
    restart: always
    container_name: telegram-bot-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx_app
    container_name: telegram-bot-nginx
    working_dir: /var/www/app
    restart: always
    depends_on:
      - php
    ports:
      - '8081:80'
      - '4443:443'
    volumes:
      - './docker/nginx/ssl-cert/nginx-selfsigned.pem:/etc/ssl/certs/nginx-selfsigned.pem'
      - './docker/nginx/ssl-cert/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key'
      - './public:/var/www/app/public:ro'

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    depends_on:
      - nginx
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
      TELEGRAM_STAT: "1 -p 8083:8082"
      TELEGRAM_LOCAL: '1'
    ports:
      - 8082:8081
